typeset -U path

GOPATH=$HOME
PLAN9=/usr/local/plan9
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LD_LIBRARY_PATH=$HOME/lib
BROWSER=webBrowser
EDITOR=vim


HISTFILE=$HOME/.zsh_history
SAVEHIST=10000
HISTSIZE=10000

path=(/home/sjf/bin $path $PLAN9/bin)

export PATH HISTFILE GOPATH PLAN9 LANG LC_ALL LANGUAGE LD_LIBRARY_PATH BROWSER EDITOR

